---
version: '3'

# setup the network
networks:
  frontend:
    external:
      name: reverse-proxy

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      # Make sure we have the same timezone as the host machine
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
    # Expose api on port 8080
    expose:
      - 8080
    # Default command used when running `docker compose up`
    command: >
      trade --logfile /freqtrade/user_data/logs/btc-ema-strategy.log --db-url sqlite:////freqtrade/user_data/databases/btc-ema-strategy.sqlite --config /freqtrade/user_data/config/btc-ema-strategy.json --strategy BTCEMAStrategy
    # add the labels to the service configuration
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # https
      - "traefik.http.routers.freqtrade.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.freqtrade.entrypoints=${ENTRYPOINT}"
      - "traefik.http.routers.freqtrade.tls=true"
      - "traefik.http.routers.freqtrade.tls.certresolver=letsencrypt"
      # middlewares
      - "traefik.http.routers.freqtrade.middlewares=redirect-to-non-www@file"
    # add the network to the service configuration
    networks:
      - frontend
