name: deploy

on:
  # run when main is pushed
  push:
    branches:
      - main
  # also run every day at midnight
  schedule:
    - cron: '23 01 * * 5'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Setup Known Hosts file
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avzh ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }}:/home/thomas/freqtrade/
      - name: Restart container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }} '(cd freqtrade && docker-compose up -d)'